pipeline {
    agent any

    stages {
        stage('hello') {
            steps {
                dir('bugtracker-backend'){
                   sh 'go test -v ./...'
                }
            }
        }
    }
}