pipeline {
    agent any

    stages {
        stage('hello') {
            steps {
                echo 'hello'
                sh 'echo "hello"'
                sh 'date'
            }
        }
    }
}